#spring.datasource.url=jdbc:postgresql://db/partstrading
#spring.datasource.username=dmparts
#spring.datasource.password=r0ys1ngh4m
#spring.jpa.hibernate.ddl-auto=none
server:
  port: 8089

google:
  clientId: myapp
  clientSecret: 4511e08a-393d-429e-8e50-9152cb029aac
  accessTokenUri: http://localhost:8082/auth/realms/demo/protocol/openid-connect/token
  userAuthorizationUri: http://localhost:8082/auth/realms/demo/protocol/openid-connect/auth
  redirectUri: http://localhost:8089/google-login
  end_session_endpoint: http://localhost:8082/auth/realms/demo/protocol/openid-connect/logout