#spring.datasource.url=jdbc:postgresql://db/partstrading
#spring.datasource.username=dmparts
#spring.datasource.password=r0ys1ngh4m
#spring.jpa.hibernate.ddl-auto=none
server:
  port: 8089

google:
  clientId: foo
  clientSecret: bar
  accessTokenUri: http://localhost:3001/token
  userAuthorizationUri: http://localhost:3001/auth
  redirectUri: http://localhost:8089/google-login